# Generated by Django 4.0.3 on 2022-03-03 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playstyle', models.CharField(default=None, max_length=20)),
                ('gunID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loadouts', to='guns.gun')),
                ('owner', models.ManyToManyField(related_name='loadaouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
