# Generated by Django 4.0.3 on 2022-03-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadout',
            old_name='playstyle',
            new_name='name',
        ),
    ]
