# Generated by Django 4.0.3 on 2022-03-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadouts', '0002_rename_playstyle_loadout_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadout',
            old_name='gunID',
            new_name='custom_gun',
        ),
    ]
