# Generated by Django 4.0.3 on 2022-03-06 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loadouts', '0003_rename_gunid_loadout_custom_gun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadout',
            name='owner',
            field=models.ManyToManyField(related_name='loadouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
