# Generated by Django 4.0.3 on 2022-03-06 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadouts', '0004_alter_loadout_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadout',
            old_name='custom_gun',
            new_name='gunID',
        ),
    ]
