# Generated by Django 4.0.3 on 2022-03-03 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=500)),
                ('attachmentsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guns', to='attachments.attachment')),
            ],
        ),
    ]
