# Generated by Django 4.0.3 on 2022-03-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
        ('guns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gun',
            name='attachmentsID',
        ),
        migrations.AddField(
            model_name='gun',
            name='attachmentsID',
            field=models.ManyToManyField(default=None, related_name='guns', to='attachments.attachment'),
        ),
    ]
